### ISSUE TITLE
Allow Documents to support 'editor'

### ISSUE THREAD

**Issue by benklocek** [wp-document-revisions/wp-document-revisions#257]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I'm trying to create a front end display of the documents with a description, and tried to add 'editor' support to the 'documents' CPT using the register_post_type_args filter. It works to display the editor, but it seems you are already using the editor for something. I see numbers in it sometimes and my changes are not saved.

### Describe the solution you'd like

My site builder (Beaver Builder) uses the_content the display excerpts and content, so I would prefer to use the default 'editor' over adding a custom field with ACF or similar, so that I can use the default implementation rather than involving other customizations.

**Comment by benbalter** [comment]
> it seems you are already using the editor for something. I see numbers in it sometimes and my changes are not saved.

I checked, and this plugin doesn't reference the `editor` field anywhere in its code base. Could it be something that's used by WordPress core or another plugin you have running? If it's a number, I suspect it's the database ID of a user.

**Comment by benklocek** [comment]
It appears to be the post ID of the most recent uploaded version saved in the editor field. Here's what I'm attempting. I wasn to be able to access the post type from the new Query Block (WP 5.8) or any other site editor, so public is true, I want to order the docs so 'page-attributes', and I want to use the editor for description so 'editor'.

I'm not seeing the Documents post type in any public list, and the editor is displaying ID for the most recently uploaded version of a document.

`add_filter( 'register_post_type_args', 'scs_change_document_post_type_args', 999, 2 );
function scs_change_document_post_type_args( $args, $post_name )
{
    if ( $post_name != 'document' )
        return $args;

    $args['public'] = true;
	$args['supports'][] = 'page-attributes';
	$args['supports'][] = 'editor';
    // other arguments

    return $args;
}`

**Comment by NeilWJames** [comment]
As Ben noted, WPDR does not use the supports Editort attribute.. The term supports means that WordPress will display and allow the user to enter data for this. This data is held in post_content. Despite not supporting the attribute, WPDR does use the field.

\Post_content is maintained internally by the plugin and contains, as stated, the post-id of the document to be attached. It is held on the post since we want to have that data on the revision in order to see the history. I can see no straight-forward way for this to be changed. (But see below).

AFAICS there is nothing specific required from the plug-in for you to use supports page-attributes effectlively. The attributes used include:
`			'publicly_queryable'   => true,
			'public'               => true,
			'show_ui'              => true,
			'show_in_menu'         => true,
			'hierarchical'         => false,`

What would the plugin need to be able to support Editor effectively (with the Block Editor) and for the content to be available as a description of the document? I believe it comes down to:
a) Store the Post-id as an HTML comment, e.g. `<!-- WPDR 1234 -->`available as
b) Parse the content for this form
This will require the Block Editor to maintain the comment in the text. This may not be true and/or there may be some constraints on this, e.g. you may have to upload the document before adding the description.

I could try some experiments but the outcome might not be as hoped for.

Neil James

**Comment by NeilWJames** [comment]
@benklocek,
I have spent some time reviewing the code - and doing some experiments.

It will be possible to provide equivalent functionality, but not in this way but using a specific block.

Some results:
1. The standard WP Query loop is not appropriate for the requirement. This is because it displays the post_excerpt field and not the post_content field. However the post_excerpt field is already used to hold the "reason for revision" data. Given the existing usage, it would be difficult to repurpose the field and the only use of the excerpt field should be via the plugin metabox.

2. The post_type is currently defined with supports excerpt. Only it doesn't really. Its use should be that it is switching on some standard WP functionality. It ought to be removed.

3. I then added editor support. This allowed the post_content field to be maintained. However this allows a complete post to be created - with all its flexibilities. And here lies a problem. I believe that what is needed for this extension is to provide a short description of the document - not a full post. It can also create problems. For example, suppose that you want to add a picture in the description. If you load an image from the editor, then it will create that image with the document post as parent. This will create inconsistent data. 

4. I can fix it by using the TinyMCE editor and setting up some parameters to essentially allow rich text input. This can include an (existing) image. However, because I need to call the TinyMCE with specific parameters, I cannot invoke the standard WP functionality since WP does not provide a filter to change from standard settings. That is, I cannot use the supports editor functionality.

5. Of course, invoking the Block Editor would make matters worse in that there is a very large set of possibilities and I am not sure how to restrict the Block Editor to accespt only a set of paragraphs and/or to restrict the image to an existing one only.

6. So the net result is that, given that we cannot sufficiently control the WP editor functionality to provide a summary description, I don't think that supports editor should be used.

7. I am able to create and maintain the post_content data to support a short description.

8. To provide the equivalent of the WP Query Loop functionality, I am looking to extend the functionality of the Lastest Documents widget to provide similar functionality including Featured Image and Summary information. I am also looking to support the text and background colours and possibly other presentation attributes now permitted.

9. Note that the block version of the Latest Document widget in version 3.3.1 of WP Docuemnt Revisions does not work with WP 5.8. The standard widget will give the same output currently.

Hope this is of use,
Neil James

**Comment by benklocek** [comment]
@neilwjames, you are a rockstar! Thank you for digging deep. This plugin is AWESOME and I would love to make it work.

I arrived at your same conclusion, so I rolled my own with an ACF "description" custom field and a custom Documents block I created to select the category and sorting and output a list with the description and link.

Many thanks again!
